apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-backend
  namespace: marketplace
  labels:
    app: marketplace-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketplace-backend
  template:
    metadata:
      labels:
        app: marketplace-backend
    spec:
      containers:
      - name: marketplace-backend
        image: roshh4/marketplace-backend-alpine-amd64:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "psql-marketplace-dev.postgres.database.azure.com"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "marketplace"
        - name: DB_USER
          value: "marketplace_admin"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: marketplace-secrets
              key: db-password
        - name: PORT
          value: "8080"
        - name: GIN_MODE
          value: "release"
        - name: DB_SSLMODE
          value: "require"
        - name: AZURE_STORAGE_ACCOUNT_NAME
          value: "marketplacestore2024"
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: marketplace-secrets
              key: storage-connection-string
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
