apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketplace-backend-ingress
  namespace: marketplace
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - secretName: marketplace-tls-secret
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: marketplace-backend-service
            port:
              number: 80
