apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: marketplace
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'marketplace-backend'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - marketplace
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: marketplace-backend
