apiVersion: v1
kind: Secret
metadata:
  name: marketplace-secrets
  namespace: marketplace
type: Opaque
data:
  # Base64 encoded values - replace with actual base64 encoded secrets
  # To encode: echo -n "your-password" | base64
  db-password: "WW91ckNob3NlblBhc3N3b3JkMTIzIQ=="
  storage-connection-string: "RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0VuZHBvaW50U3VmZml4PWNvcmUud2luZG93cy5uZXQ7QWNjb3VudE5hbWU9bWFya2V0cGxhY2VzdG9yZTIwMjQ7QWNjb3VudEtleT1EQlNScUdIazBMV3hGMUwxSEZLS3oyT0RQUVFUL1l3M0phZ2EvVnZIeXBrUk9pMUxyWllOa1ZtSDdnaDBFMTZvaFV3b3NGY0R5T2pqK0FTdGlKNVg3QT09O0Jsb2JFbmRwb2ludD1odHRwczovL21hcmtldHBsYWNlc3RvcmUyMDI0LmJsb2IuY29yZS53aW5kb3dzLm5ldC87RmlsZUVuZHBvaW50PWh0dHBzOi8vbWFya2V0cGxhY2VzdG9yZTIwMjQuZmlsZS5jb3JlLndpbmRvd3MubmV0LztRdWV1ZUVuZHBvaW50PWh0dHBzOi8vbWFya2V0cGxhY2VzdG9yZTIwMjQucXVldWUuY29yZS53aW5kb3dzLm5ldC87VGFibGVFbmRwb2ludD1odHRwczovL21hcmtldHBsYWNlc3RvcmUyMDI0LnRhYmxlLmNvcmUud2luZG93cy5uZXQvDQo="
  # Content Safety API credentials
  content-safety-key: "RVJRV0RmamlMS1pMOUNaOWwxVk9mQkp3TUVwQWZKMmFRT1R5TkNRNE05N1VmQzRiNDQwdUpRUUo5OUJKQUNxQkJMeVhKM3czQUFBQUFDT0d4ejFQ"
  content-safety-endpoint: "aHR0cHM6Ly9pbWFnZS1jb250ZW50LW1vZGVyYXRpb24uc2VydmljZXMuYWkuYXp1cmUuY29t"
