name: Build and Deploy - Main Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: rg-marketplace-dev
  AZURE_LOCATION: southeastasia

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    outputs:
      backend-url: ${{ steps.terraform-output.outputs.backend_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Generate version tag
      id: version
      run: |
        VERSION=$(date +%Y%m%d)-$(echo ${{ github.sha }} | cut -c1-7)
        echo "version=v${VERSION}" >> $GITHUB_OUTPUT
        echo "Generated version: v${VERSION}"
        
    - name: Build and push backend with version tag
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          roshh4/marketplace-backend-alpine-amd64:latest
          roshh4/marketplace-backend-alpine-amd64:${{ steps.version.outputs.version }}
        platforms: linux/amd64
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
        terraform_wrapper: false
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: |
          {
            "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
          }
          
    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          
    - name: Verify clean environment
      run: |
        echo "Current Azure account:"
        az account show --query "{subscriptionId:id, name:name, user:user.name}" --output table
        
        echo "Current resources:"
        az resource list --query "[].{name:name, type:type, resourceGroup:resourceGroup}" --output table
          
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
        
    - name: Import existing resources (if they exist)
      run: |
        cd terraform
        
        # Try to import existing resources, ignore errors if they don't exist
        terraform import -var="db_admin_password=${{ secrets.DB_PASSWORD }}" -var="container_image_tag=${{ steps.version.outputs.version }}" -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" azurerm_resource_group.marketplace "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-marketplace-dev" || true
        
        # Import existing PostgreSQL resources
        terraform import -var="db_admin_password=${{ secrets.DB_PASSWORD }}" -var="container_image_tag=${{ steps.version.outputs.version }}" -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" azurerm_postgresql_flexible_server.marketplace "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-marketplace-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psql-marketplace-dev" || true
        
        terraform import -var="db_admin_password=${{ secrets.DB_PASSWORD }}" -var="container_image_tag=${{ steps.version.outputs.version }}" -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" azurerm_postgresql_flexible_server_database.marketplace "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-marketplace-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psql-marketplace-dev/databases/marketplace" || true
        
        terraform import -var="db_admin_password=${{ secrets.DB_PASSWORD }}" -var="container_image_tag=${{ steps.version.outputs.version }}" -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" azurerm_postgresql_flexible_server_firewall_rule.azure_services "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-marketplace-dev/providers/Microsoft.DBforPostgreSQL/flexibleServers/psql-marketplace-dev/firewallRules/AllowAzureServices" || true
        
        # Import existing storage resources
        terraform import -var="db_admin_password=${{ secrets.DB_PASSWORD }}" -var="container_image_tag=${{ steps.version.outputs.version }}" -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" azurerm_storage_account.marketplace_storage "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-marketplace-dev/providers/Microsoft.Storage/storageAccounts/${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" || true

        terraform import -var="db_admin_password=${{ secrets.DB_PASSWORD }}" -var="container_image_tag=${{ steps.version.outputs.version }}" -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" azurerm_storage_container.images "https://${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/images" || true
        
        # Import existing Container App Environment
        terraform import -var="db_admin_password=${{ secrets.DB_PASSWORD }}" -var="container_image_tag=${{ steps.version.outputs.version }}" -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" azurerm_container_app_environment.marketplace "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-marketplace-dev/providers/Microsoft.App/managedEnvironments/cae-marketplace-dev" || true
        
        # Import existing Container App
        terraform import -var="db_admin_password=${{ secrets.DB_PASSWORD }}" -var="container_image_tag=${{ steps.version.outputs.version }}" -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" azurerm_container_app.marketplace_backend "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-marketplace-dev/providers/Microsoft.App/containerApps/ca-marketplace-backend-dev" || true
                
    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan \
          -var="db_admin_password=${{ secrets.DB_PASSWORD }}" \
          -var="container_image_tag=${{ steps.version.outputs.version }}" \
          -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
          
    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve \
          -var="db_admin_password=${{ secrets.DB_PASSWORD }}" \
          -var="container_image_tag=${{ steps.version.outputs.version }}" \
          -var="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}"
          
    - name: Deploy Container App
      run: |
        cd terraform
        # Get resource group and container app name
        RESOURCE_GROUP=$(terraform output -raw resource_group_name)
        CONTAINER_APP_NAME=$(terraform output -raw container_app_name)
        echo "Resource Group: ${RESOURCE_GROUP}"
        echo "Container App Name: ${CONTAINER_APP_NAME}"
        
        # Update the container app with the new image tag
        echo "Updating Container App with new image tag: ${{ steps.version.outputs.version }}"
        az containerapp update \
          --name ${CONTAINER_APP_NAME} \
          --resource-group ${RESOURCE_GROUP} \
          --image "roshh4/marketplace-backend-alpine-amd64:${{ steps.version.outputs.version }}" \
          --output none || echo "Container app update completed (may already be up to date)"
        
        # Wait for the container app to be ready
        echo "Waiting for Container App to be ready..."
        sleep 30  # Give the container app time to start
        
        # Check container app status
        echo "Checking Container App status..."
        az containerapp show \
          --name ${CONTAINER_APP_NAME} \
          --resource-group ${RESOURCE_GROUP} \
          --query "properties.runningStatus" \
          --output tsv || echo "Status check completed"
        
        echo "✅ Application deployed to Container Apps successfully!"
        
    - name: Get Backend URL from Container App
      id: terraform-output
      run: |
        cd terraform
        # Get Container App URL from Terraform output
        BACKEND_URL=$(terraform output -raw container_app_url)
        echo "backend_url=${BACKEND_URL}" >> $GITHUB_OUTPUT
        echo "Backend URL: ${BACKEND_URL}"
        
    - name: Verify Backend Health
      run: |
        BACKEND_URL="${{ steps.terraform-output.outputs.backend_url }}"
        echo "Testing backend health at: ${BACKEND_URL}/health"
        
        # Wait up to 2 minutes for backend to be ready
        for i in {1..12}; do
          if curl -k -f "${BACKEND_URL}/health" >/dev/null 2>&1; then
            echo "✅ Backend is healthy and accessible!"
            break
          fi
          echo "Attempt $i: Backend not ready yet..."
          sleep 10
        done
        
        # Final health check
        echo "Final health check:"
        curl -k -v "${BACKEND_URL}/health" || echo "⚠️ Backend health check failed, but continuing deployment"

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build frontend with backend URL
      run: |
        cd frontend
        echo "Building frontend with backend URL: ${{ needs.build-and-deploy-backend.outputs.backend-url }}"
        echo "VITE_API_URL=${{ needs.build-and-deploy-backend.outputs.backend-url }}" > .env.production
        echo "VITE_NODE_ENV=production" >> .env.production
        cat .env.production
        npm run build
        
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "./frontend"
        output_location: "dist"
        
    - name: Frontend deployment status
      run: |
        if [ -n "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ]; then
          echo "✅ Frontend deployed to Static Web App"
          echo "Frontend URL: https://ashy-coast-049069600.2.azurestaticapps.net"
        else
          echo "⚠️ Frontend deployment skipped - AZURE_STATIC_WEB_APPS_API_TOKEN not set"
          echo "Add the Static Web App deployment token to GitHub secrets"
        fi